name: python-run-install
run-name: Verifying python script and convert to .exe
on: [push]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create test file
        run: echo "140.82.114.4 Github.com Check" > input.txt
      - name: test run script
        run: python ip-retrieve.py input.txt

  install:
    needs: run-script
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          pip list
