name: release
run-name: Create Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: See env var
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"
